_target_: tum_dlr_automl_for_eo.models.classification.ClassificationTaskModule

lr: 0.001
weight_decay: 0.0005
net:
  _target_: monai.networks.nets.DenseNet169
  spatial_dims: 2
  in_channels: 1
  out_channels: 6
